name: Run SAST

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: restore dependency
      run: dotnet restore ChatApp/ChatApp.sln

    - name: build
      run: dotnet build ChatApp/ChatApp.sln

    - name: SAST run
      run: dotnet Sync_SAST/tools/net8.0/any/Sync_SAST.dll -s 'ChatApp/ChatApp.sln' -e 'SAST/output'

    - name: Upload SARIF artifact
      uses: actions/upload-artifact@v4
      with:
        name: sarif-results
        path: SAST/output/ChatApp-output.sarif

    - name: Upload SARIF to DefectDojo
      run: |
        curl -X POST http://localhost:61015/api/v2/import-scan/ \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
        -F 'file=@output/results.sarif' \
        -F 'scan_type=SARIF' \
        -F 'engagement=1' \
        -F 'product_id=1' \
        -F 'minimum_severity=Low' \
        -F 'active=true' \
        -F 'verified=true' \
        -F 'scan_date=${{ github.event.head_commit.timestamp }}' \
        -F 'close_old_findings=false'

      
