name: Run SAST

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: restore dependency
      run: dotnet restore ChatApp/ChatApp.sln

    - name: build
      run: dotnet build ChatApp/ChatApp.sln

    - name: SAST run
      run: dotnet Sync_SAST/tools/net8.0/any/Sync_SAST.dll -s 'ChatApp/ChatApp.sln' -e 'SAST/output.sarif'

    - name: Upload SARIF artifact
      uses: actions/upload-artifact@v4
      with:
        name: sarif-results
        path: output/results.sarif
      
